clients:
    # Type
    type: simple_he

    # The total number of clients
    total_clients: 50

    # encrypt ratio
    encrypt_ratio: 0.2
    random_mask: False

    compute_comm_time: True

    # The number of clients selected in each round
    per_round: 10
    
    # Should the clients compute test accuracy locally?
    do_test: false

    # Processors for outbound data payloads
    outbound_processors:
        # - unstructured_pruning
        - model_encrypt
    inbound_processors:
        - model_decrypt

server:
    address: 127.0.0.1
    port: 8070
    random_seed: 1
    simulate_wall_time: true

    type: fedavg_homo_enc

data:
    # The training and testing dataset
    datasource: Texas

    # Number of samples in each partition
    partition_size: 1078

    num_classes: 100

    # IID or non-IID?
    sampler: iid

    # The random seed for sampling data
    random_seed: 1

trainer:
    # The type of the trainer
    type: basic_gradient
    # type: diff_privacy
    # dp_epsilon: 2
    # dp_delta: 0.00001
    # dp_max_grad_norm: 1

    # The maximum number of training rounds
    rounds: 20

    # The maximum number of clients running concurrently
    max_concurrency: 4

    # The target accuracy
    target_accuracy: 0.99

    # Number of epoches for local training in each communication round
    epochs: 5
    batch_size: 32
    optimizer: SGD
    learning_rate: 0.01
    momentum: 0.9
    weight_decay: 0.0

    # The machine learning model
    model_name: multilayer
    input_dim: 6169
    num_classes: 100

algorithm:
    # Aggregation algorithm
    type: fedavg

results:
    # Write the following parameter(s) into a CSV
    types: round, elapsed_time, accuracy, comm_time

    # Plot results (x_axis-y_axis)
    plot: round-accuracy, elapsed_time-accuracy
