
general:

    # performing different running mode
    # for different purposes
    # - central_code_test
    # - central
    # - script
    # - code_test
    # - user

    running_mode: script

    file_logging: True

clients:
    # Type
    type: simple

    # The total number of clients
    total_clients: 50

    # The number of clients selected in each round
    per_round: 50

    # Should the clients compute test accuracy locally?
    do_test: True

    # Minotor the self-supervised learning by knn for
    # every 5 round
    test_interval: 1

    # Whether simulate clients or not
    simulation: true

    random_seed: 1

server:
    address: 127.0.0.1
    port: 8012
    synchronous: true
    do_test: true

    # for the paths of models; checkpoints; results,
    # they utilize the same name, following the one defined in
    # plato.config:
    # {ssl_method_name}_{model_name}_{global_model_name}_{personalized_model_name}_{datasource}
    # - ssl_method_name: data.augment_transformer_name
    # - model_name: trainer.model_name
    # - global_model_name: data.global_model_name
    # - personalized_model_name: data.personalized_model_name
    # - datasource: data.datasource

    # set xxx here as the config will set the path by itself
    # thus we do not need to repeatly reset these paths
    model_path: xxx
    checkpoint_path: xxx


data:
    # The training and testing dataset
    datasource: MNIST

    # Number of samples in each partition
    #
    # This is one important parameter that
    # may lead the failure of the loss criterion part
    # if your loss criterion relies on the batch_size
    # as its argument. For example, the NT_Xent loss utilized
    # by the SimCLR method set the defined batch_size as the parameter.
    # However, at the end of one epoch, the left samples may smaller than
    # the batch_size. This makes the #loaded samples != batch_size.
    # Working on criterion that is defined with batch_size but receives loaded
    # samples whose size is smaller than the batch size may causes problems.
    # drop_last can alleviate this issue
    partition_size: 1000


    # IID or non-IID?
    sampler: noniid
    testset_sampler: noniid

    # The concentration parameter for the Dirichlet distribution
    concentration: 0.5

    # The concentration parameter for the Dirichlet distribution
    # sampler: noniid
    # testset_sampler: noniid
    # concentration: 0.1

    # The random seed for sampling data
    random_seed: 1


trainer:
    # The type of the trainer
    type: basic
    # The maximum number of training rounds
    rounds: 1

    # Whether the training should use multiple GPUs if available
    parallelized: false

    # The maximum number of clients running concurrently
    max_concurrency: 5

    # The target accuracy
    target_accuracy: 0.98


    # Number of epochs for local training in each communication round
    #   The user is expected to carefully choose the batch_size to avoid
    # the memory allocation issue as the contrastive samples occupy more
    # space as more samples will be contained within one loading.
    epochs: 50
    batch_size: 64
    optimizer: Adam
    learning_rate: 0.003
    betas:
      - 0.9
      - 0.999
    eps: 0.00000008 # 1e-8
    weight_decay: 0.001

    lr_scheduler: StepLR
    lr_step_size: 20
    lr_gamma: 0.9

    epoch_log_interval: 2
    batch_log_interval: 5

    # The machine learning model,
    # it behaves as the encoder for the ssl method
    # the final fc layer will be removed
    # however, in the central test, we do not use this
    #   but use the custom model
    model_name: lenet5

    num_classes: 10

algorithm:
    # Aggregation algorithm
    type: fedavg

results:
    result_path: xxx